// <auto-generated />
using System;
using Eventos.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Eventos.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Eventos.Domain.Entities.Eventos.Evento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int?>("CapacidadActual")
                        .HasColumnType("int")
                        .HasColumnName("capacidad_actual");

                    b.Property<int?>("CapacidadMaxima")
                        .HasColumnType("int")
                        .HasColumnName("capacidad_maxima");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime?>("FechaEvento")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_evento");

                    b.Property<Guid?>("IdUsuario")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nombre");

                    b.Property<string>("Ubicacion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ubicacion");

                    b.HasKey("Id")
                        .HasName("pk_eventos");

                    b.HasIndex("IdUsuario")
                        .HasDatabaseName("ix_eventos_id_usuario");

                    b.ToTable("eventos", (string)null);
                });

            modelBuilder.Entity("Eventos.Domain.Entities.Inscripciones.Inscripcion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("EventoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("evento_id");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_creacion");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_inscripciones");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_inscripciones_usuario_id");

                    b.ToTable("inscripciones", (string)null);
                });

            modelBuilder.Entity("Eventos.Domain.Entities.Users.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Apellido")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("apellido");

                    b.Property<string>("Email")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("email");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("Nombre")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("nombre");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_email")
                        .HasFilter("[email] IS NOT NULL");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("Eventos.Domain.Entities.Eventos.Evento", b =>
                {
                    b.HasOne("Eventos.Domain.Entities.Users.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .HasConstraintName("fk_eventos_usuario_id_usuario");
                });

            modelBuilder.Entity("Eventos.Domain.Entities.Inscripciones.Inscripcion", b =>
                {
                    b.HasOne("Eventos.Domain.Entities.Users.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .HasConstraintName("fk_inscripciones_usuario_usuario_id");
                });
#pragma warning restore 612, 618
        }
    }
}
